In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)




In [4]:
from keras.utils import to_categorical
data_train = pd.read_csv('../my files/fashion-mnist_train.csv')
data_test = pd.read_csv('../my files/fashion-mnist_test.csv')

X_train = np.array(data_train.iloc[:, 1:])
X_test = np.array(data_test.iloc[:, 1:])
y_train = to_categorical(np.array(data_train.iloc[:, 0]))
y_test = to_categorical(np.array(data_test.iloc[:, 0]))

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [5]:
print(X_train)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [6]:
print(X_train.shape)

(60000, 784)


In [7]:
print(y_train.shape)

(60000, 10)


In [8]:
print(X_test.shape)

(10000, 784)


In [9]:
print(y_test.shape)

(10000, 10)


In [15]:
print(X_train.shape[0])   # no. of rows of X_train  = no. of training samples
print(X_train.shape[1])   # no. of columns of X_train   =no. of features of a sample
print(y_train.shape[0])   # no. of rows of y_train  = no. of training samples
print(y_train.shape[1])   # no. of columns of y_train  =no. of binary digits of a test sample

print(X_test.shape[0])   # no. of rows of X_test  = no. of test samples
print(X_test.shape[1])   # no. of columns of X_test
print(y_test.shape[0])   # no. of rows of y_test
print(y_test.shape[1])   # no. of columns of y_test


60000
784
60000
10
10000
784
10000
10


In [13]:
img_rows, img_cols = 28, 28
X_train = X_train.reshape(X_train.shape[0], img_rows, img_cols, 1)
X_test = X_test.reshape(X_test.shape[0], img_rows, img_cols, 1)
input_shape = (img_rows, img_cols, 1)

X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255

In [15]:
print(y_train)

[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


In [18]:
print(X_train[1])


[[[0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]]

 [[0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]]

 [[0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0. 

In [19]:
print(y_train[1])


[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


In [17]:
print(X_train[1].shape)
print(y_train[1].shape)

(784,)
(10,)


In [23]:
print(y_train[200])

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


In [28]:
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout, Flatten, Conv2D, MaxPooling2D

input_shape = (img_rows, img_cols, 1)
model = Sequential()
model.add(Conv2D(32, kernel_size=(5, 5),
                 activation='relu',
                 input_shape=input_shape))
model.add(MaxPooling2D(pool_size=(2, 2)))
#model.add(Dropout(0.25))
model.add(Conv2D(64, (5, 6), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
#model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(250, activation='relu'))
#model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))
model.compile(optimizer='adam',
          loss='categorical_crossentropy',
          metrics=['accuracy'])

In [29]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 24, 24, 32)        832       
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 12, 12, 32)        0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 8, 7, 64)          61504     
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 4, 3, 64)          0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 768)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 250)               192250    
_________________________________________________________________
dense_4 (Dense)              (None, 10)                2510      
Total para

In [30]:
model.fit(X_train, y_train,
          batch_size=50,
          epochs=3,
          verbose=1,
          validation_data=(X_test, y_test))
score = model.evaluate(X_test, y_test, verbose=0)

Train on 60000 samples, validate on 10000 samples
Epoch 1/3
60000/60000 [==============================] - 5585s 93ms/step - loss: 0.4811 - acc: 0.8254 - val_loss: 0.3376 - val_acc: 0.8801
Epoch 2/3
60000/60000 [==============================] - 19733s 329ms/step - loss: 0.3099 - acc: 0.8870 - val_loss: 0.2972 - val_acc: 0.8914
Epoch 3/3
60000/60000 [==============================] - 35092s 585ms/step - loss: 0.2636 - acc: 0.9041 - val_loss: 0.2621 - val_acc: 0.9020


In [31]:
print('accuracy: ',score[1])
print('loss: ',score[0])

accuracy:  0.902
loss:  0.2620717862963676
